name: CI/CD  
  
on:  
  push:  
    branches:
      main  
  
jobs:
  build:
    uses: agahalou96/github-actions-reusable/.github/workflows/main.yml@main
    with:
      login-server: githubactionsreusableregistry.azurecr.io 
    secrets:
      registry-username: ${{ secrets.REGISTRY_USERNAME }}
      registry-password: ${{ secrest.REGISTRY_PASSWORD }}
